const data = window.MORANT_FAMILY_DATA;
const branchGrid = document.querySelector('#branchGrid');
const branchSelect = document.querySelector('#branchSelect');
const formBranch = document.querySelector('#formBranch');
const notifyBranch = document.querySelector('#notifyBranch');
const registrationBranch = document.querySelector('#registrationBranch');
const branchDetail = document.querySelector('#branchDetail');
const branchPanel = document.querySelector('#branchPanel');
const searchBox = document.querySelector('#searchBox');
const directoryResults = document.querySelector('#directoryResults');
const familyForm = document.querySelector('#familyForm');
const notificationForm = document.querySelector('#notificationForm');
const registrationForm = document.querySelector('#registrationForm');
const submissionList = document.querySelector('#submissionList');
const registrationList = document.querySelector('#registrationList');

const asPerson = item => typeof item === 'string' ? { name: item, years: '' } : item;
const label = person => { const p = asPerson(person); return `${p.name}${p.years ? ` <span class="years">${p.years}</span>` : ''}${p.note ? ` <em>${p.note}</em>` : ''}`; };
function getStored(key) { return JSON.parse(localStorage.getItem(key) || '[]'); }
function setStored(key, items) { localStorage.setItem(key, JSON.stringify(items, null, 2)); }
const getSubmissions = () => getStored('morantFamilySubmissions');
const saveSubmissions = items => setStored('morantFamilySubmissions', items);
const getNotifications = () => getStored('morantNotificationSignups');
const saveNotifications = items => setStored('morantNotificationSignups', items);
const getRegistrations = () => getStored('morantReunionRegistrations');
const saveRegistrations = items => setStored('morantReunionRegistrations', items);
const getPendingGrandchildren = () => getStored('morantPendingGrandchildren');
const savePendingGrandchildren = items => setStored('morantPendingGrandchildren', items);

function openBranchPanel() { branchPanel?.classList.add('is-open'); }
function countSavedPhotos() { return Object.keys(localStorage).filter(key => key.startsWith('morantPhoto:') || key === 'morantHeroLogo').length; }
function updateHonestStats() {
  document.querySelectorAll('.stats-grid div').forEach(card => {
    const labelText = card.querySelector('small')?.textContent?.trim().toLowerCase() || '';
    if (labelText.includes('photos')) { card.querySelector('strong').textContent = String(countSavedPhotos()); card.querySelector('small').textContent = 'Uploaded Photos'; }
    if (labelText.includes('stories')) { card.querySelector('strong').textContent = '0'; card.querySelector('small').textContent = 'Stories Added'; }
    if (labelText.includes('documents')) { card.querySelector('strong').textContent = '0'; card.querySelector('small').textContent = 'Documents Added'; }
  });
}
function setAdminMode(isOn) {
  document.body.classList.toggle('admin-mode', isOn);
  localStorage.setItem('morantAdminMode', isOn ? 'true' : 'false');
  const button = document.querySelector('.login-btn');
  if (button) button.textContent = isOn ? 'Admin: On' : 'Admin Login';
}
function setupAdminMode() {
  setAdminMode(localStorage.getItem('morantAdminMode') === 'true');
  const button = document.querySelector('.login-btn');
  if (!button) return;
  button.setAttribute('href', '#');
  button.addEventListener('click', event => {
    event.preventDefault();
    setAdminMode(!document.body.classList.contains('admin-mode'));
  });
}
function setupHeroLogoUpload() { const area = document.querySelector('.editable-logo-area'); const input = document.querySelector('#heroLogoUpload'); const preview = document.querySelector('#heroLogoPreview'); const remove = document.querySelector('#removeHeroLogo'); if (!area || !input || !preview) return; const savedLogo = localStorage.getItem('morantHeroLogo'); if (savedLogo) { preview.src = savedLogo; area.classList.add('logo-ready'); } input.addEventListener('change', () => saveImageInput(input, 'morantHeroLogo', dataUrl => { preview.src = dataUrl; area.classList.add('logo-ready'); updateHonestStats(); })); remove?.addEventListener('click', () => { localStorage.removeItem('morantHeroLogo'); preview.removeAttribute('src'); area.classList.remove('logo-ready'); input.value = ''; updateHonestStats(); }); }
function compressImageFile(file, maxSize = 900, quality = 0.72) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = reject; reader.onload = () => { const img = new Image(); img.onerror = reject; img.onload = () => { const scale = Math.min(1, maxSize / Math.max(img.width, img.height)); const canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round(img.width * scale)); canvas.height = Math.max(1, Math.round(img.height * scale)); const ctx = canvas.getContext('2d'); ctx.drawImage(img, 0, 0, canvas.width, canvas.height); resolve(canvas.toDataURL('image/jpeg', quality)); }; img.src = reader.result; }; reader.readAsDataURL(file); }); }
async function saveImageInput(input, key, onSaved) { const file = input.files?.[0]; if (!file) return; try { const dataUrl = await compressImageFile(file); localStorage.setItem(key, dataUrl); onSaved(dataUrl); updateHonestStats(); } catch (error) { console.error(error); alert('That photo could not be saved on this device. Try a smaller image, or clear old uploaded photos. Backend storage will remove this limit.'); } }
function photoUploader(id, labelText = 'Add Photo') { const saved = localStorage.getItem(`morantPhoto:${id}`); return `<label class="profile-photo-upload ${saved ? 'has-photo' : ''}" title="Upload photo"><img src="${saved || ''}" alt="${labelText} profile photo" /><span>▣<br>${labelText}</span><input type="file" accept="image/*" data-photo-id="${id}" /></label><button class="photo-remove" type="button" data-remove-photo="${id}">Remove Photo</button>`; }
function setupPhotoUploads(scope = document) { scope.querySelectorAll('[data-photo-id]').forEach(input => { input.addEventListener('change', () => { const id = input.dataset.photoId; saveImageInput(input, `morantPhoto:${id}`, dataUrl => { const holder = input.closest('.profile-photo-upload'); const img = holder.querySelector('img'); img.src = dataUrl; holder.classList.add('has-photo'); }); }); }); scope.querySelectorAll('[data-remove-photo]').forEach(button => { button.addEventListener('click', () => { const id = button.dataset.removePhoto; localStorage.removeItem(`morantPhoto:${id}`); const parent = button.closest('.branch-card, .photo-card, .generation-card, .profile-photo-block') || document; const holder = parent.querySelector(`[data-photo-id="${id}"]`)?.closest('.profile-photo-upload'); if (holder) { holder.classList.remove('has-photo'); holder.querySelector('img').removeAttribute('src'); holder.querySelector('input').value = ''; } updateHonestStats(); }); }); }
function setupRootPhotoUploads() { const cards = document.querySelectorAll('.root-photos .photo-card'); const ids = ['bobbie-ruff', 'cornella-morant-ruff']; cards.forEach((card, index) => { if (!card.querySelector('.profile-photo-upload')) card.insertAdjacentHTML('afterbegin', photoUploader(ids[index] || `root-${index}`, 'Add Photo')); }); setupPhotoUploads(document.querySelector('.root-photos') || document); }
function allPeople() { const people = []; data.rootCouple.forEach(root => people.push({ name: root.name, years: root.years, branch: 'Founding Elders', generation: root.role || 'Founding Elder' })); data.maternalAncestry.forEach(person => people.push({ ...person, branch: 'Maternal Ancestry', generation: 'Documented ancestor / relative' })); data.branches.forEach(branch => { people.push({ name: branch.name, years: branch.years, branch: branch.name, generation: 'Parent Group / Branch Elder' }); branch.children.forEach(child => { const p = asPerson(child); people.push({ name: p.name, years: p.years, branch: branch.name, generation: 'Child / Beneficiary' }); }); branch.grandchildren.forEach(group => group.names.forEach(grandchild => { const p = asPerson(grandchild); people.push({ name: p.name, years: p.years, branch: branch.name, generation: `Grandchild of ${group.parent}` }); })); }); getPendingGrandchildren().forEach(item => people.push({ name: item.childName, years: '', branch: item.branchName, generation: `Pending child of ${item.parentName}` })); return people; }
function renderBranchCards() { branchGrid.innerHTML = data.branches.map(branch => `<article class="branch-card" style="--branch-color:${branch.color}"><p class="eyebrow">Parent Group</p><h3>${branch.name}</h3>${photoUploader(`branch-${branch.id}`, 'Add Photo')}${branch.years ? `<p class="years big-years">${branch.years}</p>` : ''}<button type="button" data-branch-button="${branch.id}">Open Parent Group</button></article>`).join(''); setupPhotoUploads(branchGrid); document.querySelectorAll('[data-branch-button]').forEach(button => { button.addEventListener('click', () => { openBranchPanel(); branchSelect.value = button.dataset.branchButton; renderBranchDetail(button.dataset.branchButton); branchPanel?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }); }); }
function renderSelects() { const options = data.branches.map(branch => `<option value="${branch.id}">${branch.name}</option>`).join(''); [branchSelect, formBranch, notifyBranch, registrationBranch].filter(Boolean).forEach(select => select.innerHTML = options); }
function renderHeritage() { const heritage = document.querySelector('#heritageContent'); const ancestry = document.querySelector('#ancestryList'); if (!heritage || !ancestry) return; heritage.innerHTML = `<h3>${data.heritage.title}</h3><p>${data.heritage.summary}</p><p class="note">${data.heritage.note}</p>`; ancestry.innerHTML = '<p class="note">Detailed ancestor names are available through search or admin-approved profile pages.</p>'; }
function renderGrandchildList(branch) { const confirmed = branch.grandchildren || []; const pending = getPendingGrandchildren().filter(item => item.branchId === branch.id); const confirmedHtml = confirmed.map(group => `<li><strong>${group.parent}</strong>${group.names?.length ? `<ul>${group.names.map(person => `<li>${label(person)}</li>`).join('')}</ul>` : '<small>No children listed yet.</small>'}</li>`).join(''); const pendingHtml = pending.length ? `<h5>Pending additions saved on this device</h5><ul>${pending.map(item => `<li><strong>${item.childName}</strong><small> child of ${item.parentName}</small>${item.note ? `<em>${item.note}</em>` : ''}</li>`).join('')}</ul>` : ''; return `<ul>${confirmedHtml || '<li class="empty-slot">No grandchildren listed yet.</li>'}</ul>${pendingHtml}`; }
function renderChildEntryForm(branch) { if (!branch.children?.length) return '<p class="empty-slot">Add child slots first before adding grandchildren.</p>'; const options = branch.children.map(child => { const p = asPerson(child); return `<option value="${p.name}">${p.name}</option>`; }).join(''); return `<div class="child-entry-card"><h3>Add Children / Grandchildren</h3><p>Select the parent in this branch, then add their child. For Pamela branch, choose Mathew McCaster to add your children under your mother’s grandchildren.</p><form id="grandchildForm"><label>Parent in this branch<select name="parentName">${options}</select></label><label>Child name<input name="childName" required placeholder="Full name" /></label><label>Notes / years / relationship<textarea name="note" rows="3" placeholder="Birth year, relationship, or spelling notes"></textarea></label><button type="submit">Save Pending Child</button></form></div>`; }
function setupGrandchildForm(branch) { const form = document.querySelector('#grandchildForm'); if (!form) return; const select = form.querySelector('select[name="parentName"]'); if (branch.id === 'pamela' && [...select.options].some(option => option.value === 'Mathew McCaster')) select.value = 'Mathew McCaster'; form.addEventListener('submit', event => { event.preventDefault(); const formData = new FormData(form); const item = { branchId: branch.id, branchName: branch.name, parentName: formData.get('parentName'), childName: formData.get('childName'), note: formData.get('note'), createdAt: new Date().toISOString() }; const items = getPendingGrandchildren(); items.unshift(item); savePendingGrandchildren(items); renderBranchDetail(branch.id); alert('Saved as a pending child/grandchild update on this device.'); }); }
function renderBranchDetail(branchId = '') { if (!branchId) { branchDetail.innerHTML = '<div class="callout">Select a parent group to view the first generation beneath that parent. Full descendant names remain hidden unless a branch is opened or searched.</div>'; return; } openBranchPanel(); const branch = data.branches.find(item => item.id === branchId); if (!branch) return; const childList = branch.children.length ? branch.children.map((child, index) => `<li>${photoUploader(`child-${branch.id}-${index}`, 'Photo')}${label(child)}</li>`).join('') : '<li class="empty-slot">Children not listed yet</li>'; branchDetail.innerHTML = `<div class="branch-title"><div><p class="eyebrow">Opened Parent Group</p><h2>${branch.name}</h2>${branch.years ? `<p class="years big-years">${branch.years}</p>` : ''}</div><span>${branch.children.length} children listed</span></div><div class="generation-grid"><article class="generation-card"><h4>Children / Beneficiaries</h4><ul>${childList}</ul></article><article class="generation-card"><h4>Grandchildren / Next Generation</h4>${renderGrandchildList(branch)}</article></div>${renderChildEntryForm(branch)}`; setupPhotoUploads(branchDetail); setupGrandchildForm(branch); }
function renderDirectory(filter = '') { const q = filter.trim().toLowerCase(); if (!q) { directoryResults.innerHTML = '<p class="note">Start typing to reveal matching names. The full list is not displayed publicly.</p>'; return; } const people = allPeople().filter(person => person.name.toLowerCase().includes(q) || person.branch.toLowerCase().includes(q)); directoryResults.innerHTML = people.map(person => `<div class="directory-item"><div class="profile-photo-block">${photoUploader(`search-${person.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`, 'Photo')}</div><strong>${person.name}</strong><span>${person.years ? `${person.years} • ` : ''}${person.generation} • ${person.branch}</span></div>`).join('') || '<p>No matches found.</p>'; setupPhotoUploads(directoryResults); }
function renderSubmissions() { const items = getSubmissions(); submissionList.innerHTML = items.map(item => `<div class="submission-item"><strong>${item.submitter || 'Unnamed submission'} — ${item.branchName}</strong><pre>${item.familyMembers || 'No details entered yet.'}</pre><small>${new Date(item.createdAt).toLocaleString()}</small></div>`).join('') || '<p class="note">No saved family update drafts yet.</p>'; }
function renderRegistrations() { if (!registrationList) return; const items = getRegistrations(); registrationList.innerHTML = items.map(item => `<div class="submission-item"><strong>${item.name || 'Unnamed registration'} — ${item.branchName}</strong><p>${item.adults || 0} adults • ${item.children || 0} children • Hotel: ${item.hotel || 'No'}</p><small>${new Date(item.createdAt).toLocaleString()}</small></div>`).join('') || '<p class="note">No saved registration drafts yet.</p>'; }
function downloadCsv(filename, rows) { const csv = rows.map(row => row.map(cell => `"${String(cell ?? '').replaceAll('"', '""')}"`).join(',')).join('\n'); const blob = new Blob([csv], { type: 'text/csv' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = filename; a.click(); URL.revokeObjectURL(url); }
function downloadRegistryCsv() { const rows = [['Name', 'Years', 'Branch', 'Generation']]; allPeople().forEach(person => rows.push([person.name, person.years || '', person.branch, person.generation])); downloadCsv('morant-family-bloodline-registry.csv', rows); }
function downloadNotificationsCsv() { const rows = [['Name', 'Branch', 'Email', 'Phone', 'Email Updates', 'Text Updates', 'Created']]; getNotifications().forEach(item => rows.push([item.name, item.branchName, item.email, item.phone, item.emailOptIn ? 'Yes' : 'No', item.textOptIn ? 'Yes' : 'No', item.createdAt])); downloadCsv('morant-reunion-notification-signups.csv', rows); }
function downloadRegistrationsCsv() { const rows = [['Name', 'Branch', 'Email', 'Phone', 'Adults', 'Children', 'Shirts', 'Hotel', 'Notes', 'Created']]; getRegistrations().forEach(item => rows.push([item.name, item.branchName, item.email, item.phone, item.adults, item.children, item.shirts, item.hotel, item.notes, item.createdAt])); downloadCsv('morant-reunion-registrations.csv', rows); }
function downloadReunionICS() { const ics = `BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Morant Family Reunion//EN\nCALSCALE:GREGORIAN\nMETHOD:PUBLISH\nBEGIN:VEVENT\nUID:morant-family-reunion-2026@morantfamilyreunion.com\nDTSTAMP:20260704T120000Z\nSUMMARY:Morant Family Reunion 2026\nLOCATION:San Antonio, Texas\nDESCRIPTION:Morant Family Reunion 2026. Final schedule and details to be confirmed by family administrators.\nDTSTART;VALUE=DATE:20260701\nDTEND;VALUE=DATE:20260702\nEND:VEVENT\nEND:VCALENDAR`; const blob = new Blob([ics.replaceAll('\\n','\r\n')], { type: 'text/calendar;charset=utf-8' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'morant-family-reunion-2026.ics'; a.click(); URL.revokeObjectURL(url); }
function notificationSummary() { return `${getNotifications().length} saved notification signup${getNotifications().length === 1 ? '' : 's'}`; }
function updateNotificationSummary() { const target = document.querySelector('#notificationSummary'); if (target) target.textContent = notificationSummary(); }
function setupNotificationTools() { const section = document.querySelector('#updates'); if (!section || section.querySelector('#notificationTools')) return; section.insertAdjacentHTML('beforeend', `<div id="notificationTools" class="notification-tools admin-only"><strong id="notificationSummary">${notificationSummary()}</strong><button id="testNotification" type="button">Test Save</button><button id="downloadNotificationsVisible" type="button">Download Signups CSV</button><p class="admin-note">Current version saves signups on this device and exports CSV. Live email/text blast requires backend storage plus email/SMS connection.</p></div>`); document.querySelector('#testNotification')?.addEventListener('click', () => alert(`Notification system is saving locally. ${notificationSummary()}.`)); document.querySelector('#downloadNotificationsVisible')?.addEventListener('click', downloadNotificationsCsv); updateNotificationSummary(); }
function setupCalendarTools() { const card = document.querySelector('#reunion'); if (!card || card.querySelector('#downloadCalendar')) return; card.insertAdjacentHTML('beforeend', '<button id="downloadCalendar" type="button" class="red-btn calendar-btn">Add to Calendar</button><p class="admin-note">Downloads an .ics calendar file for San Antonio, TX. Date is a placeholder until family admins confirm final schedule.</p>'); document.querySelector('#downloadCalendar')?.addEventListener('click', downloadReunionICS); }
function markAdminOnly() { document.querySelectorAll('#downloadNotifications,#downloadNotificationsVisible,#testNotification,#downloadCsv,#downloadRegistrations,#printBranch,#clearSubmissions,#copySubmission,#registrationList,#submissionList').forEach(el => el.classList.add('admin-only')); }

setupAdminMode(); setupHeroLogoUpload(); renderBranchCards(); setupRootPhotoUploads(); renderSelects(); renderHeritage(); renderBranchDetail(''); renderDirectory(''); renderSubmissions(); renderRegistrations(); setupCalendarTools(); setupNotificationTools(); updateHonestStats(); markAdminOnly();
branchSelect.addEventListener('change', event => { openBranchPanel(); renderBranchDetail(event.target.value); });
searchBox.addEventListener('input', event => renderDirectory(event.target.value));
document.querySelector('#downloadCsv').addEventListener('click', downloadRegistryCsv);
document.querySelector('#printBranch').addEventListener('click', () => window.print());
document.querySelector('#downloadNotifications')?.addEventListener('click', downloadNotificationsCsv);
document.querySelector('#downloadRegistrations')?.addEventListener('click', downloadRegistrationsCsv);
notificationForm?.addEventListener('submit', event => { event.preventDefault(); const form = new FormData(notificationForm); const branch = data.branches.find(item => item.id === form.get('branch')); const item = Object.fromEntries(form.entries()); item.branchName = branch?.name || item.branch; item.emailOptIn = form.has('emailOptIn'); item.textOptIn = form.has('textOptIn'); item.createdAt = new Date().toISOString(); const items = getNotifications(); items.unshift(item); saveNotifications(items); notificationForm.reset(); notifyBranch.value = data.branches[0].id; updateNotificationSummary(); alert('Saved to the reunion update list on this device. Live email/text blasts need backend connection.'); });
registrationForm?.addEventListener('submit', event => { event.preventDefault(); const form = new FormData(registrationForm); const branch = data.branches.find(item => item.id === form.get('branch')); const item = Object.fromEntries(form.entries()); item.branchName = branch?.name || item.branch; item.createdAt = new Date().toISOString(); const items = getRegistrations(); items.unshift(item); saveRegistrations(items); renderRegistrations(); registrationForm.reset(); registrationBranch.value = data.branches[0].id; alert('Registration saved as a draft on this device. Next step: connect this to the live database.'); });
familyForm.addEventListener('submit', event => { event.preventDefault(); const form = new FormData(familyForm); const branch = data.branches.find(item => item.id === form.get('branch')); const item = Object.fromEntries(form.entries()); item.branchName = branch?.name || item.branch; item.createdAt = new Date().toISOString(); const items = getSubmissions(); items.unshift(item); saveSubmissions(items); renderSubmissions(); familyForm.reset(); formBranch.value = data.branches[0].id; alert('Family update saved as a draft on this device.'); });
document.querySelector('#copySubmission').addEventListener('click', async () => { const [latest] = getSubmissions(); if (!latest) return alert('No family update draft to copy yet.'); const text = `Morant Family Bloodline Submission\n\nName: ${latest.submitter}\nEmail: ${latest.email}\nBranch: ${latest.branchName}\nRelationship: ${latest.relationship}\n\nFamily Members:\n${latest.familyMembers}\n\nMedia Notes:\n${latest.mediaNotes}`; await navigator.clipboard.writeText(text); alert('Latest family update copied.'); });
document.querySelector('#clearSubmissions').addEventListener('click', () => { if (confirm('Clear saved family update drafts on this device?')) { saveSubmissions([]); renderSubmissions(); } });